version: '3.5'
services:
  redis1:
    image: redis:5.0.7
    hostname: redis1
    command: redis-server --bind 0.0.0.0 --protected-mode "no" --appendonly "yes" --cluster-enabled yes --cluster-announce-ip 192.168.241.133 --port 10001
    networks:
      - host
    extra_hosts:
      - "redis1:192.168.241.133"
      - "redis2:192.168.241.134"
      - "redis3:192.168.241.135"
    volumes:
      - "redis:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.redis1 == true
    environment:
      - "TZ=Asia/Shanghai"
      

  redis2:
    image: redis:5.0.7
    hostname: redis2
    command: redis-server --bind 0.0.0.0 --protected-mode "no" --appendonly "yes" --cluster-enabled yes --cluster-announce-ip 192.168.241.134 --port 10001
    networks:
      - host
    extra_hosts:
      - "redis1:192.168.241.133"
      - "redis2:192.168.241.134"
      - "redis3:192.168.241.135"
    volumes:
      - "redis:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.redis2 == true
    environment:
      - "TZ=Asia/Shanghai"
      

  redis3:
    image: redis:5.0.7
    hostname: redis3
    command: redis-server --bind 0.0.0.0 --protected-mode "no" --appendonly "yes" --cluster-enabled yes --cluster-announce-ip 192.168.241.135 --port 10001
    networks:
      - host
    extra_hosts:
      - "redis1:192.168.241.133"
      - "redis2:192.168.241.134"
      - "redis3:192.168.241.135"
    volumes:
      - "redis:/data"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.redis3 == true
    environment:
      - "TZ=Asia/Shanghai"
      


networks:
  host:
    external: true

volumes:
  redis:


